language: node_js
node_js:
 - "node"


cache: npm

jobs:
  include:
      script: npm run test:unit
    - stage: build  
      script: npm run build
      deploy:
        provider: npm
        email: "NPM_EMAIL"
        api_key: "NPM_AUTH"


