language: node_js
node_js:
 - "12"
cache: yarn

install:
  - yarn install
jobs:
  include:
    - stage: Test
      script:
        - yarn test:unit
    - stage: NPM Release
      script: yarn build
      deploy:
        provider: npm
        email: 'alphacentorus@gmail.com'
        api_key: '$NPM_AUTH'
        skip_cleanup: true
        on:
          tags: true
branches:
only:
  - main
  - /^v[0-9]+.*$/


